PLUS, MINUS, MUL, DIV, REAL_DIV, MOD, EOF, RPAREN, LPAREN, LESS, GREATER, EQUAL, NOT_EQUAL, LESS_EQ, GREATER_EQ = (
    'PLUS', 'MINUS', 'MUL', 'DIV', 'REAL_DIV', 'MOD', 'EOF', 'RPAREN', 'LPAREN', 'LESS', 'GREATER', 'EQUAL',
    'NOT_EQUAL',
    'LESS_EQ', 'GREATER_EQ'
)

ID = 'ID'
USE = 'USE'
COND = 'COND'
LOOND = 'LOOND'
RETURN = 'RETURN'
TYPE = 'TYPE'
HASH = 'HASH'
RBRACKET = 'RBRACKET'
LBRACKET = 'LBRACKET'
DOT = 'DOT'
SEMICOLON = 'SEMICOLON'
COLON = 'COLON'
ASSIGN = 'ASSIGN'
COMMA = 'COMMA'
DEC = 'DEC'
DECFUN = 'DECFUN'
APOSTROPHE = 'APOSTROPHE'

# var_and_function types:
STRING = 'STRING'
BOOLEAN = 'BOOLEAN'
FLOAT = 'FLOAT'
INTEGER = 'INTEGER'
ARRAY = 'ARRAY'
DO = 'DO'

# unar operations:
NOT = 'NOT'

# Logic operations:
AND = 'AND'
OR = 'OR'
