INTEGER, PLUS, MINUS, MUL, DIV, EOF, RPAREN, LPAREN, LESS, GREATHER, EQUAL, NOT_EQUAL, LESS_EQ, GREATHER_EQ  = (
    'INTEGER', 'PLUS', 'MINUS', 'MUL', 'DIV', 'EOF', 'RPAREN', 'LPAREN', 'LESS', 'GREATHER', 'EQUAL', 'NOT_EQUAL', 'LESS_EQ', 'GREATHER_EQ'
)

ID = 'ID'
USE = 'USE'
TYPE = 'TYPE'
HASH = 'HASH'
RBRACKET = 'RBRACKET'
LBRACKET = 'LBRACKET'
DOT = 'DOT'
SEMICOLON = 'SEMICOLON'
COLON = 'COLON'
ASSIGN = 'ASSIGN'
COMMA = 'COMMA'
DEC = 'DEC'

STRING = 'STRING'
BOOLEAN = 'BOOLEAN'
FLOAT = 'FLOAT'
APOSTROPHE = 'APOSTROPHE'

