PLUS, MINUS, MUL, DIV, EOF, RPAREN, LPAREN, LESS, GREATER, EQUAL, NOT_EQUAL, LESS_EQ, GREATER_EQ = (
    'PLUS', 'MINUS', 'MUL', 'DIV', 'EOF', 'RPAREN', 'LPAREN', 'LESS', 'GREATER', 'EQUAL', 'NOT_EQUAL',
    'LESS_EQ', 'GREATER_EQ'
)

ID = 'ID'
USE = 'USE'
TYPE = 'TYPE'
HASH = 'HASH'
RBRACKET = 'RBRACKET'
LBRACKET = 'LBRACKET'
DOT = 'DOT'
SEMICOLON = 'SEMICOLON'
COLON = 'COLON'
ASSIGN = 'ASSIGN'
COMMA = 'COMMA'
DEC = 'DEC'
DECFUN = 'DECFUN'

#var types:
STRING = 'STRING'
BOOLEAN = 'BOOLEAN'
FLOAT = 'FLOAT'
INTEGER = 'INTEGER'
APOSTROPHE = 'APOSTROPHE'

#unar operations:
NOT = 'NOT'

#Logic operations:
AND = 'AND'
OR = 'OR'